version: "3.3"
services:
  app:
    build:
      args:
        user: ubuntuwsl
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: secretariado
    container_name: secretariado-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:alpine
    container_name: secretariado-nginx
    restart: unless-stopped
    ports:
      - 8700:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/

